DROP TABLE USER_RELATED_GAME;
DROP TABLE GAME_INFO;
DROP TABLE USER_INFO;

CREATE TABLE USER_INFO (
  USER_ID VARCHAR(30) NOT NULL,
  USER_NAME VARCHAR(32) NOT NULL UNIQUE,
  USER_PWD VARCHAR(16) NOT NULL,
  USER_SCORE INTEGER NOT NULL ,
  USER_WINNUM INTEGER NOT NULL ,
  USER_LOSENUM INTEGER NOT NULL ,
  PRIMARY KEY(USER_ID)
);

CREATE TABLE GAME_INFO (
	GAME_ID VARCHAR(30) NOT NULL,
	GAME_START_TIME VARCHAR(30) NOT NULL,
	GAME_LAST_TIME VARCHAR(30) NOT NULL,
	FIRST_USER_ID VARCHAR(30) NOT NULL,
	SECOND_USER_ID VARCHAR(30) NOT NULL,
	THIRD_USER_ID VARCHAR(30) NOT NULL,
	foreign key (FIRST_USER_ID) references USER_INFO(USER_ID) on delete cascade,
	foreign key (SECOND_USER_ID) references USER_INFO(USER_ID) on delete cascade,
	foreign key (THIRD_USER_ID) references USER_INFO(USER_ID) on delete cascade,
	PRIMARY KEY(GAME_ID)
);

CREATE TABLE USER_RELATED_GAME (
	USER_ID VARCHAR(30) NOT NULL,
	GAME_ID VARCHAR(30) NOT NULL,
	USER_SIGN INTEGER NOT NULL,
	USER_SCORE INTEGER NOT NULL,
	PRIMARY KEY(USER_ID, GAME_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
	FOREIGN KEY (GAME_ID) REFERENCES GAME_INFO(GAME_ID) ON DELETE CASCADE
);