DROP TABLE GAME_REPLAY_RECORD;
CREATE TABLE GAME_REPLAY_RECORD (
  GAME_ID VARCHAR(30) NOT NULL,
  USER_ID VARCHAR(30) NOT NULL,
  CARD_RECORD VARCHAR(60) NOT NULL,
  PLAY_TIME VARCHAR(30) NOT NULL,
  INDEX(GAME_ID)
);